# Site settings
title: theRingleman
header-img: img/home-bg.png
email: sam.ringleman@gmail.com
copyright_name: theRingleman
description: > # this means to ignore newlines until "baseurl:"
  My Journey through this awesome world of code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: theRingleman
github_username:  theRingleman
learn_profile: theRingleman
email_username: sam.ringleman@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
